name = "carboniq"
compatibility_date = "2024-09-30"

[build]
command = "pnpm build:cf"
cwd = ""

[build.upload]
format = "modules"

[env.production.vars]
NODE_ENV = "production"
# Add your production environment variables here
# FIREBASE_API_KEY = "your-api-key"
# FIREBASE_AUTH_DOMAIN = "your-auth-domain"
# FIREBASE_PROJECT_ID = "your-project-id"

[env.preview.vars]
NODE_ENV = "preview"
# Add your preview environment variables here
