# This file is for Cloudflare Pages configuration
# For Git integration, most settings are configured in the Cloudflare Pages dashboard
# This file is kept minimal to avoid CLI deployment conflicts

name = "carboniq"
compatibility_date = "2024-09-30"
