name = "carboniq"
compatibility_date = "2024-09-30"
pages_build_output_dir = "dist/spa"

[build]
command = "pnpm build"

[[pages.env_vars]]
name = "NODE_ENV"
value = "production"

[env.production.vars]
# Add your production environment variables here
# FIREBASE_API_KEY = "your-api-key"
# FIREBASE_AUTH_DOMAIN = "your-auth-domain"
# FIREBASE_PROJECT_ID = "your-project-id"

[env.preview.vars]
# Add your preview environment variables here
